---

version: '2.3'

services:
  server:
    image: unbound:unbound-zone-feeder
    build:
      context: unbound
    ports:
      - "127.0.0.1:5300:53"
      - "127.0.0.1:5300:53/udp"
    networks:
      - control
  web:
    image: httpd:unbound-zone-feeder
    build:
      context: http
    networks:
      - content
  provider:
    image: unbound-zone-feeder:latest
    build:
      context: ..
    command: [
      "-b", "docker.io",
      "-b", "spam.expl0.it",
      "-b", "malware.inval.id",
      "-w", "grayi.sh", # whitelist host from blacklist.txt
      "-f", "/blacklist.txt",
      "-u", "http://web/hosts.txt",
      "-z", "always_nxdomain",
      "-r", "2",
      "-v",
      "-i",
      "-d", "1",
      "--metrics"
    ]
    environment:
      UZF_HOST: server
    volumes:
      - type: bind
        source: ./blacklist.txt
        target: /blacklist.txt
        read_only: true
    ports:
      - "127.0.0.1:5380:8080"
    networks:
      - control
      - content
    depends_on:
      - server
      - web

networks:
  control:
  content:
